# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'SigmaSwiftStatistics', '~> 1.1'
pod 'SCLAlertView'
pod 'ASValueTrackingSlider'
pod 'Charts'

target 'Guess Correlation Plus' do

end

